# Site settings
title: Christophe Dufour
description: > # this means to ignore newlines until "baseurl:"
  My blog about technical stuff I want to share.
url: "http://www.christophe-dufour.fr" # the base hostname & protocol for your site
twitter_username: christof_dufour
github_username:  christophe-dufour

# Build settings
markdown: kramdown

baseurl: /

paginate:         5

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

gems:
  - jekyll-archives
  - jekyll-sitemap